name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/TeamUp
        run: npm test
      
      - name: Check MongoDB connection
        run: |
          echo "Checking MongoDB connection"
          netstat -tuln


  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test # Ensures this job runs only if 'test' job succeeds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Render
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/deploy/${RENDER_SERVICE_ID}" \
          -H "Authorization: Bearer ${RENDER_API_TOKEN}"
